version: '3'
services:
  postgresql:
    container_name: postgres_wall_street
    image: postgres:latest
    environment:
      - POSTGRES_USER=wall_street
      - POSTGRES_PASSWORD=wall_street
      - POSTGRES_DB=wall_street
      - POSTGRES_HOST_AUTH_METHOD=md5
    ports:
      - '5432:5432'
